print(f'-------------------------------------------------------------------------------')
print(f'NOTE:')
print(f'This product does not include Front-End Electronics (sensor).')
print(f'The following limits and features are present:')
print(f' - Enabling the sensor is not possible.')
print(f' - Image Captures are not possible.')
print(f' - 10 Sessions are pre-loaded on the Imager to allow read outs to be performed.')
print(f' - It is not possible to delete sessions 1 to 10.')
print(f' - The Delete All command has also been disabled.')
print(f'-------------------------------------------------------------------------------')
